[package]
name = "scale-info-gen"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "Apache-2.0"
repository = "https://github.com/paritytech/scale-info"
documentation = "https://docs.rs/scale-info"
homepage = "https://www.parity.io/"
description = "Generate types from a type registry instance"

[dependencies]
proc-macro2 = "1.0"
quote = "1"
syn = { version = "1.0", features = ["parsing", "full"] }
scale = { package = "parity-scale-codec", version = "1.3", default-features = false}
scale-info = { version = "0.4", path = "..", features = ["derive"] }

[lib]
proc-macro = true
