[package]
name = "scale-info-gen"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "Apache-2.0"
repository = "https://github.com/paritytech/scale-info"
documentation = "https://docs.rs/scale-info"
homepage = "https://www.parity.io/"
description = "Generate types from TypeInfo instances"

[dependencies]
scale-info = { version = "0.3.0", path = "..", default-features = false, features = ["dogfood"] }
