name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup
      run: |
        rustup install nightly --profile default

    - name: fmt
      run: |
        cargo +nightly fmt --version
        cargo +nightly fmt --all -- --check

    - name: clippy
      run: |
        cargo +nightly clippy --version
        cargo +nightly clippy --all -- -D warnings

    - name: build
      run: |
        cargo --version --verbose
        cargo build --all
        cargo build --all --no-default-features

    - name: test
      run: |
        cargo test --all

    - name: test no-std
      run: |
        cd ./test_suite/derive_tests_no_std
        cargo +nightly build --no-default-features


